
services:
  sysmon:
    container_name: sysmon
    build: .
    command: tail -F __not_exists__
    stop_grace_period: 1s
    network_mode: host
    volumes:
      - ./logs:/home/ezd/logs
    # ports:
    #   - ${POSTGRES_PORT}:${POSTGRES_PORT}
    #   - ${EZD_API_PORT}:${EZD_API_PORT}
    # depends_on:
    #   - postgres
    environment:
      # - PORT=${EZD_API_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
